var words = [
    "Weatherford",
    "OutThere",
    "MU",
    "Beavs",
    "Benny Beaver",
    "Mole Hole",
    "The Dam",
    "LIC", 
    "LiNC", 
    "Women's Building", 
    "Panda Express", 
    "Java II", 
    "Javastop", 
    "Bullpen", 
    "26th Street", 
    "Campus Way", 
    "Kerr", 
    "Kelley", 
    "Our Beautiful Home", 
    "Corvallis", 
    "Valley Library", 
    "Austin", 
    "Buxton", 
    "Milam", 
    "Dearborn", 
    "Stag", 
    "Reser", 
    "Gill", 
    "Kidder", 
    "Goss Stadium", 
    "SAC", 
    "Milne", 
    "Waldo", 
    "ALS", 
    "1868", 
    "Go Beavs!", 
    "Jefferson", 
    "OSU", 
    "Benton", 
    "Dixon", 
    "Bell Tower", 
    "Batcheller", 
    "Dearborn", 
    "Bexell", 
    "Beavers", 
    "football", 
    "06 & 07 Baseball Champs", 
    "Sun Grant", 
    "Sea Grant", 
    "Space Grant", 
    "Sun Grant", 
    "OSU150", 
    "Ada Kidder", 
    "Canvas", 
    "CLA", 
    "CoE", 
    "Pharmacy", 
    "Craft Center", 
    "Honors College", 
    "INTO", 
    "KidSpirit", 
    "Linus Pauling", 
    "ONID", 
    "The Writing Center", 
    "WIC", 
    "SMS", 
    "Emp Center", 
    "Exmail", 
    "Marketplace West", 
    "McNary", "Arnold", 
    "Trader Bing's", 
    "Cascadia Deli", 
    "Peet's Coffee", 
    "e.Cafe", 
    "Calabaloo's", 
    "Cooper's Creek", 
    "EBGBs", 
    "Ring of Fire", 
    "Serrano", 
    "541", 
    "97333", 
    "Five Four One", 
    "La Calle", 
    "RainTree Coffee", 
    "The Main Squeeze", 
    "Boardwalk Cafe", 
    "Tomassito's", 
    "Bites", 
    "Joe's Burgers", 
    "North Porch", 
    "Pangea", 
    "TOGO's", 
    "Bing's Cafe", 
    "Interzone", 
    "Yogurt Extreme", 
    "QDoba", 
    "Dutch Bros", 
    "Starbucks", 
    "Clods", 
    "the bookstore", 
    "LaSells", 
    "Vet Med", 
    "People's Park", 
    "Gilfillan", ];

var random = words[Math.floor(Math.random() * words.length)];

var paragraph = 

function generator() {
    $("#OSU").html(random);
}
